### ISSUE TITLE
Refactor code to allow better separation/inspection of transaction data

### ISSUE THREAD

**Issue by taylorSando** [SparkFund/spec-tacular#17]
I'd like write a datomic ACL and I'd like to be able to preview changes without actually using transact, by using datomic/with.  One option would be to change conn-ctx so that it takes a transact function, which would either be the actual datomic/transact function, or it would be a partial function, e.g., (partial datomic/with (datomic/db conn)) which would be applied to the transaction data.

Either that, or further break up the side effecting code, so that I can get all the transaction data easier.  I already split up create-graph!, into a non side-effecting create-graph.  The other functions don't seem like they would take too much time to change, and it doing it that way wouldn't change the conn-ctx semantics.

**Comment by calvis** [comment]
> One option would be to change conn-ctx so that it takes a transact function

If the field (like a `:transaction-function` key) is not supplied we could use the the Datomic `transact` as a default, otherwise use the transaction function supplied.  

However, the supplied function would have to take the same arguments as the `transact` function and have the same return type.  The return value of the call to `transact` is used by `create-graph!` to produce a representation of the entities that were created, which wouldn't be possible if the transaction function didn't actually commit them.  If we wanted to allow redefining the transaction function, we'd also have to allow redefining the code that  "processes the return value of transaction function".  I'm not sure if that makes sense, or what the right abstraction would be, so I'll have to think on that.

> or further break up the side effecting code

It sounds to me like you're asking for a better interface to `transaction-data` (i.e. the function that actually turns spec instances into transaction data).  Would a `graph->transaction-data` function be the right interface?  I'm imagining that `graph->transaction-data` would have the same arguments as `create-graph!` but would return just the data.  A similar function for `create!` would be `instance->transaction-data`.

A third option - maybe adding `:dry-run` or `:preview-only` option to the `conn-ctx` would work?

**Comment by taylorSando** [comment]
The second option seems easiest, and does what I want, I think.  The third option would be interesting if you wanted to be able to get back preview instances, which might fit another use case, but I think what I want to be able to do is get the transaction data, run it through db/with, then take tx-data and run it through db-before and db-after, and classify each add/retraction as either :create, :update, or :delete.

**Comment by calvis** [comment]
So, I added `graph-transaction-data` (which was from the PR you created then deleted -- I can rebase out your commit if you'd prefer) and `instance-graph-transaction` as of b7b78184a8fabc08a427f7207056b68b39c2c5fc, let me know if there's something missing.
